### ISSUE TITLE
questions about dlgm_nf.py

### ISSUE THREAD

**Issue by ifangcheng** [thu-ml/zhusuan#101]
1.  in line 74-76 in  dlgm_nf.py :
    qz_samples, log_qz = zs.planar_normalizing_flow(qz_samples, log_qz,
                                                    n_iters=n_planar_flows)
    qz_samples, log_qz = zs.planar_normalizing_flow(qz_samples, log_qz,
                                                    n_iters=n_planar_flows)

why repeat the codes? if we want to implement more layers of normalizing_flow.why not just set the
n_iters directly?  e.g. 
    qz_samples, log_qz = zs.planar_normalizing_flow(qz_samples, log_qz,
                                                    n_iters=2*n_planar_flows)

2.  what's the parameters in normalizing_flow?  can these parameters also be optimized during 
the training process?

**Comment by meta-inf** [comment]
1. It seems like an outdated sanity check - thanks for pointing out. You certainly can fold them. 
2. Yes. You can check the doc string for the math of the transformation and reference.
