### ISSUE TITLE
Collaboration with TensorLayer

### ISSUE THREAD

**Issue by DEKHTIARJonathan** [thu-ml/zhusuan#107]
Hello dear friends,

I have been reading your work with much interest. With @zsdonghao @luomai @lgarithm we maintain the library TensorLayer (TL), https://github.com/tensorlayer/tensorlayer.

I think that your work can be really complementary to TL APIs.

Maybe you would be interested in working together and heading toward a common direction.

We have a chat group on Slack and/or WeChat if you wanna talk.

Have a nice day,

All the best,

Jonathan DEKHTIAR

**Comment by thjashin** [comment]
Oh Sorry I missed the message. 

Thank you for reaching out. And glad that you are interested in ZhuSuan.
Just have a look through TL and see my favorite Lassagne API :)
Do you have any plan in mind at this time?

**Comment by DEKHTIARJonathan** [comment]
It was more like a message to open the discussion and why not set up a conference on WeChat or a group chat ;)

**Comment by zsdonghao** [comment]
@DEKHTIARJonathan thanks Jonathan.  @thjashin hello, feel free to let us know if you want to have a chat via Wechat, Skype or others ~ : D

**Comment by thjashin** [comment]
@DEKHTIARJonathan @zsdonghao That sounds great. Would love to chat. How about Wechat?

**Comment by zsdonghao** [comment]
hi, please add me: zsdh123
