### ISSUE TITLE
save and restore models?

### ISSUE THREAD

**Issue by ifangcheng** [thu-ml/zhusuan#108]
Just wondering how to save and restore  trained deep generative models in zhusuan?
So that we can deploy or continue to train the previous trained models? 
Is it  exactly the same with that for general  tensorflow models?

**Comment by thjashin** [comment]
Hi. Yes, it's just the same. The only thing you need to be careful about is that `zs.reuse` will add another level of scope.

**Comment by ifangcheng** [comment]
1. Thanks for the reply!  Any examples to show that?
2. If we can save and restore the pre-trained  deep generative models in zhusuan,  is it possible to use the "fine tune" trick to do transfer learning for DGMs?  e.g. whether we can fine tune a DGM trained on cifar10, to get a better DGM for a special domain with my own small dataset?

**Comment by thjashin** [comment]
Basically it will look like this:
```python
    saver = tf.train.Saver(max_to_keep=10)
    logger = setup_logger('vae_conv', __file__, result_path)

    with tf.Session() as sess:
        sess.run(tf.global_variables_initializer())

        # Restore from the latest checkpoint
        ckpt_file = tf.train.latest_checkpoint(result_path)
        begin_epoch = 1
        if ckpt_file is not None:
            logger.info('Restoring model from {}...'.format(ckpt_file))
            begin_epoch = int(ckpt_file.split('.')[-2]) + 1
            saver.restore(sess, ckpt_file)

        for epoch in range(begin_epoch, epochs + 1):
             ....

            if epoch % save_model_freq == 0:
                logger.info('Saving model...')
                save_path = os.path.join(result_path,
                                         "vae.epoch.{}.ckpt".format(epoch))
                if not os.path.exists(os.path.dirname(save_path)):
                    os.makedirs(os.path.dirname(save_path))
                saver.save(sess, save_path)
                logger.info('Done')
```

**Comment by ifangcheng** [comment]
many thanks!
