### ISSUE TITLE
请问哪里能找到zhusuan的中文文档?

### ISSUE THREAD

**Issue by dofish** [thu-ml/zhusuan#110]
rt

**Comment by thjashin** [comment]
There is currently no documents in Chinese

**Comment by dofish** [comment]
是不是中文不太好用?-__-!!

**Comment by csy530216** [comment]
我感觉主要是维护起来比较麻烦，两边要同步。多看看英语挺好的:) 虽然这英语是中国人写的233

**Comment by dofish** [comment]
楼上的兄弟,回帖中透着一股淡淡的忧桑和无奈.
