### ISSUE TITLE
Memory leaks caused by VariationalObjective

### ISSUE THREAD

**Issue by ZicongZhang** [thu-ml/zhusuan#115]
Hi, I am currently developing VAE based on the donut library. I found memory leak when restoring saved model multi times. I checked the program with objgraph and found the following chain:
![](https://user-images.githubusercontent.com/30051794/53776522-454afb00-3f31-11e9-8fd6-939bcafbc3ed.png)

You could see from this figure that the module zhusuan hold a static variable without release. I checked code in the zhusuan library and found two @classmethod that create static variables in zhusuan.variational.base.py 

![](https://user-images.githubusercontent.com/30051794/53776904-960f2380-3f32-11e9-9e5d-c83d798498eb.png)

I solved the leak problem we are facing by release the static variables explicit after we finish the function. I think you could figure out how to fix this issue in zhusuan.

**Comment by thjashin** [comment]
Hi, thanks for reporting this. we are currently redesigning variational inference functionalities, and these will be fixed in a newer version.

**Comment by thjashin** [comment]
Resolved in #119 and will be soon into master. Please reopen the issue if the problem still exists @ZicongZhang .
