### ISSUE TITLE
module 'tensorflow' has no attribute 'make_template'

### ISSUE THREAD

**Issue by JonvoWoo** [thu-ml/zhusuan#125]
When I run the code of vae in the example floder, there is an error, says " AttributeError                            Traceback (most recent call last)
<ipython-input-2-3f00f9adc4c9> in <module>()
----> 1 @zs.reuse_variables(scope="q_net")
      2 def build_q_net(x, z_dim, n_z_per_x):
      3     bn = zs.BayesianNet()
      4     h = tf.layers.dense(tf.cast(x, tf.float32), 500, activation=tf.nn.relu)
      5     h = tf.layers.dense(h, 500, activation=tf.nn.relu)

G:\anaconda\lib\site-packages\zhusuan\framework\utils.py in <lambda>(f)
    104         <https://www.tensorflow.org/api_docs/python/tf/variable_scope>`_.
    105     """
--> 106     return lambda f: tf.make_template(scope, f)
    107 
    108 

AttributeError: module 'tensorflow' has no attribute 'make_template'
"
Is this error related to the tensorflow2.0 I am using?

**Comment by thjashin** [comment]
Hi,

Please use TF 1.X at the moment.
We are planning to support 2.0 soon.

Best,
Jiaxin

**Comment by steffenvan** [comment]
Have you implemented this for 2.0 yet? I still get the same AttributeError.
