### ISSUE TITLE
cant install ZhuSuan

### ISSUE THREAD

**Issue by ghost** [thu-ml/zhusuan#128]
I run the command: pip install https://github.com/thu-ml/zhusuan.git. in command promt. But I got an error during the downloading this package: can not unpack the file.
Could you help me with the installation of the Zhusuan?

**Comment by thjashin** [comment]
Hi, please follow the installation guide in README.

**Comment by ghost** [comment]
@thjashin Hi. I did that as I said:  pip install https://github.com/thu-ml/zhusuan.git. in command promt. But I had an error: can not unpack the file.

**Comment by csy530216** [comment]
@neginjv You can try
```bash
git clone https://github.com/thu-ml/zhusuan.git
cd zhusuan
pip install .
```

**Comment by ghost** [comment]
@csy530216 thanks a lot.
