### ISSUE TITLE
Ancestral sampling incorrect (?)

### ISSUE THREAD

**Issue by meta-inf** [thu-ml/zhusuan#42]
Code below should output close to 0 according to the docs, but the output is actually random.

```
import tensorflow as tf
import zhusuan as zs
if __name__ == "__main__":
  with zs.BayesianNet() as model:
    z = zs.Normal('z', tf.constant(0.), tf.constant(0.))
    x = zs.Normal('x', z, tf.constant(0.))
    spl = x.sample(1000)
  with tf.Session() as sess:
    print(sess.run(tf.reduce_mean(spl)))
```

**Comment by thjashin** [comment]
Be careful that you get one sample from `z` and 1000 samples conditioned on that `z`. So the mean you get should be approximately the same with that `z`. If you average over multiple sess.run, you should get 0.

**Comment by meta-inf** [comment]
I know. I just think it's not a very good user experience...

**Comment by thjashin** [comment]
@meta-inf  I think it is. It should be even in concept. A single run of this model in concept is not guaranteed to  produce something near 0.
