### ISSUE TITLE
Extending Bayesian NNs to have more hidden layers

### ISSUE THREAD

**Issue by hoangcuong2011** [thu-ml/zhusuan#64]
Greetings Jiaxin,

I am playing with regression using Bayesian Neural Networks. To do so I use your code (https://github.com/thu-ml/zhusuan/blob/master/examples/tutorials/bayesian_nn.py).

Thank you for writing such a great framework (zhusuan) and for your bayesian_nn code. 

I have a question though: Could you give me instructions on how to extend the code to have more layers (let's say, 3 layers instead of only 1)?

Is that complicated to do that? In Edward it is pretty easy but I am not sure in this case.

If it is very easy, I hope to ask you a favor of doing that. Meanwhile if it is not the case, please give me some hints and then I will try to implement.

Thank you for your time, and again, thank you for your great framework!

**Comment by thjashin** [comment]
Yes it's easy. If you take a closer look at the code, it actually has taken multi-layer cases into consideration.
```python
# Define model parameters
n_hiddens = [50]
```
If the above snippet is changed to
```python
# Define model parameters
n_hiddens = [50, 50]
```
It will be a two-layer Bayesian NN.

btw, the Bayesian NN code in the tutorial directory will soon be merged with the other one [here](https://github.com/thu-ml/zhusuan/blob/master/examples/bayesian_neural_nets/bayesian_nn.py). It has caused some confusion to have two similar pieces of code in the example repository.

**Comment by hoangcuong2011** [comment]
Thank you @thjashin for having a pretty clear/instructive answer. I appreciate your help a lot!
