### ISSUE TITLE
No module named examples

### ISSUE THREAD

**Issue by rzhangpku** [thu-ml/zhusuan#65]
When I run the examples, such as `python zhusuan/examples/bayesian_neural_nets/python bayesian_nn.py`, I will get the error "ImportError: No module named examples". Please help me. Thank you.

**Comment by lzkmylz** [comment]
You can use code as follow to add path to your zhusuan dir:
import sys
sys.path.append('Your zhusuan path')

**Comment by thjashin** [comment]
Hi @rzhangpku , since we have organized the examples as a package (python does not allow running modules in it as a script), you could use
```python
python -m examples.bayesian_neural_nets.bayesian_nn
```
in the main directory.

**Comment by thjashin** [comment]
And thank @lzkmylz for the solution, which will work also.

**Comment by thjashin** [comment]
Anyone has a good idea about how to organize the example scripts into sub directories but still keep them runnable as a script? Contributions welcome.

**Comment by rzhangpku** [comment]
@thjashin It works, thank you very much!

**Comment by rzhangpku** [comment]
@lzkmylz Thank you for your solution!
