### ISSUE TITLE
Questions on multivariate distributions class

### ISSUE THREAD

**Issue by jsxzljx** [thu-ml/zhusuan#82]
Dear authors, thanks for the great package. I have some questions here and would like to ask for some help.

### Initialize a distribution

In [Basic Concepts](http://zhusuan.readthedocs.io/en/latest/tutorials/concepts.html#distribution) part of the docs, the code 
```python
>>> import zhusuan as zs
>>> a = zs.distributions.Normal(mean=0., logstd=0.)
```
is easy to understand and I think it represents we create a random variable a~N(0, 0), while

``` python
>>> b = zs.distributions.Normal([[-1., 1.], [0., -2.]], [0., 1.])
```
seems confusing to me. Does it mean we create a 2*2 random variables which form a matrix? If is, what does `[0., 1.]` means then ?

### multivariate distributions

In the [Bayesian Neural Networks for Multivariate Regression](http://zhusuan.readthedocs.io/en/latest/tutorials/bayesian_nn.html#build-the-model) section of the docs, the code below is a little bit confusing to me.

``` python
with zs.BayesianNet(observed=observed) as model:
    ws = []
    for i, (n_in, n_out) in enumerate(zip(layer_sizes[:-1],
                                          layer_sizes[1:])):
        w_mu = tf.zeros([1, n_out, n_in + 1])
        ws.append(
            zs.Normal('w' + str(i), w_mu, std=1.,
                      n_samples=n_particles, group_ndims=2))
```
The doc says "The last `group_ndims` number of axes in batch_shape are grouped into a single event". In this case, the `batch_shape` is `[n_out, n_in + 1]` and the `value_shape` is `[]`, setting `group_ndims=2` means we group the n_out*(n_in + 1) random variables together so as to evaluate the probability at one time, right?

If the understanding above  is correct, then I notice we just create n_out*(n_in + 1) random variables which are independent with each other, we can also treat them as a multivariate Normal random variable with identity covariance matrix. However, what if I want to create a *real* multivariate Normal random variable with a non-diagonal covariance matrix? I didn't see it in `module-zhusuan.distributions.multivariate` while this kind class exists in tensorflow (refer to [tf.contrib.distributions.MultivariateNormalDiag](https://www.tensorflow.org/versions/master/api_docs/python/tf/contrib/distributions/MultivariateNormalDiag)).

Hope it's not much work and thanks for your time!

PS. I think that the basic concept part of docs may be relatively hard for people who have limited background on this topic (like me), though the expression is mathematically precise indeed. Hope for more vivid figures and easy examples to illustrate the abstract concepts. :)

**Comment by thjashin** [comment]
@jsxzljx Thanks for posting it here. 

> If is, what does [0., 1.] means then

In general, distributions support clever broadcasting for inputs. For univariate Normal, it will broadcast the mean and std to have the same shape. Thanks for pointing this out. I'll updated the docs to show this.

**Comment by jsxzljx** [comment]
@thjashin thanks for your reply😊. So what about the multivariate Normal distribution with a non-diagonal covariance matrix then?

**Comment by thjashin** [comment]
We are working on it. See #77

**Comment by thjashin** [comment]
And also contributions are welcomed to improve the docs since users may have a very different perspective. If you find any other places unclear, just raise a issue or change it and send us a PR. We'd appreciate it.

**Comment by jsxzljx** [comment]
Okay, I got it.  Many thanks for your work and help.
