### ISSUE TITLE
no variational  parameters 

### ISSUE THREAD

**Issue by ifangcheng** [thu-ml/zhusuan#91]
in line 51 of  /toy_examples/toy2d_intractable.py :
infer_op = optimizer.minimize(cost)

it seems that the variational parameters( z_mean, z_logstd) were not explicitly specified,  how does the
optimizer knows exactly which parameters to optimize?

**Comment by thjashin** [comment]
Tensorflow optimizer will optimize over all `tf.trainable_variables()` if no `var_list` is given.

**Comment by ifangcheng** [comment]
ok, I see. thx!
