### ISSUE TITLE
how to output a whole distribution?

### ISSUE THREAD

**Issue by TingqiIC** [thu-ml/zhusuan#92]
In bayesian_nn example, y_pred is the mean value of the distribution used to represent the prediction. Instead of printing out the mean value, how can I get the whole distribution of it(i.e. an interval)?

**Comment by miskcoo** [comment]
Did you mean to get the confidence interval of y? If so, you can return y_mean and y_logstd (the two parameters completely determine the normal distribution), and use scipy.stats.norm.ppf to compute the $\alpha$-quantile.

**Comment by TingqiIC** [comment]
Thanks I will have a try.
