### ISSUE TITLE
two questions about vae_conv.py

### ISSUE THREAD

**Issue by ifangcheng** [thu-ml/zhusuan#94]
1.  in line 84： x_test = np.random.binomial(1, x_test, size=x_test.shape).astype('float32')
    the dtype of x_test is 'float32
    in line 110:   x = tf.placeholder(tf.int32, shape=[None, n_x], name='x')
    the dtype of x is tf.int32,  it seems that x_test  is not match x.
    however, in line 165:     feed_dict={x: test_x_batch,
    test_x_batch is feed to x ,    and the program works well,  why?

2. in line 66:         lz_x = layers.dropout(lz_x, keep_prob=0.9, is_training=is_training) 
The dropout layer is applied after a bn layer.
Considering that they have some similar effects (e.g. regulation), is it a good operation to use both bn and dropout tricks? Any further benefits can we get than just use one of them ?

**Comment by thjashin** [comment]
> in line 84： x_test = np.random.binomial(1, x_test, size=x_test.shape).astype('float32')
the dtype of x_test is 'float32
in line 110: x = tf.placeholder(tf.int32, shape=[None, n_x], name='x')
the dtype of x is tf.int32, it seems that x_test is not match x.
however, in line 165: feed_dict={x: test_x_batch,
test_x_batch is feed to x , and the program works well, why?

1. Seems that `sess.run` will work out the conversion.

> in line 66: lz_x = layers.dropout(lz_x, keep_prob=0.9, is_training=is_training)
The dropout layer is applied after a bn layer.
Considering that they have some similar effects (e.g. regulation), is it a good operation to use both bn and dropout tricks? Any further benefits can we get than just use one of them ?

2. This is an old example that hasn't been heavily tuned. The settings are quite arbitrary. We should update it some time.

**Comment by thjashin** [comment]
FYI. I've updated the convolutional vae example. It has a simpler implementation (without bn/dropout or any other tricks) but has very good test performance.
